### PR TITLE
Don't set initial value if element has property

### LINKED ISSUE #108: It's not possible to instantiate `GeneratedVaadinTimePicker` subclass whose value is based on the underlying Element value
This is failing test:

```

private static LocalTime TEST_VALUE = LocalTime.now();

private static class TestTimePicker
            extends GeneratedVaadinTimePicker<TestTimePicker, LocalTime> {

        TestTimePicker() {
            super(TEST_VALUE, null, String.class, value -> null, value -> null);
        }
    }

@Test
    public void elementHasValue_wrapIntoField_propertyIsNotSetToInitialValue() {
        Element element = new Element("vaadin-time-picker");
        element.setProperty("value", "10:15");
        UI ui = new UI();
        UI.setCurrent(ui);
        VaadinSession session = Mockito.mock(VaadinSession.class);
        ui.getInternals().setSession(session);
        VaadinService service = Mockito.mock(VaadinService.class);
        Mockito.when(session.getService()).thenReturn(service);

        Instantiator instantiator = Mockito.mock(Instantiator.class);

        Mockito.when(service.getInstantiator()).thenReturn(instantiator);

        Mockito.when(instantiator.createComponent(TimePicker.class))
                .thenAnswer(invocation -> new TimePicker(LocalTime.now()));

        TimePicker field = Component.from(element, TimePicker.class);
        Assert.assertEquals("10:15",
                field.getElement().getPropertyRaw("value"));
    }
```

### PR DESCRIPTION
**Pull request by denis-anisimov**
Fixes #108

### CODE REVIEW

File: vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java [hunk 1]
```diff
@@ -839,6 +839,10 @@ protected Registration addInvalidChangeListener(
     /**
      * Constructs a new GeneratedVaadinTimePicker component with the given
      * arguments.
+     * <p>
+     * If {@code isInitialValueOptional} is {@code true} then the initial value
+     * is used only if element has no {@code "value"} property value, otherwise
+     * element {@code "value"} property is ignored and the initial value is set.
```
Comment (mshabarov) [inline vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java:845]: I propose to remove this paragraph, because exactly the same explanation is given below for `isInitialValueOptional ` parameter and it looks excessive.

File: vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java [hunk 2]
```diff
@@ -921,6 +929,6 @@ public GeneratedVaadinTimePicker(T initialValue, T defaultValue,
      */
     public GeneratedVaadinTimePicker() {
         this(null, null, null, (SerializableFunction) null,
-                (SerializableFunction) null);
+                (SerializableFunction) null, true);
```
Comment (mshabarov) [inline vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java]: Here the initial value is optional, contrary to `combo box`. What is the difference?

File: vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java [hunk 3]
```diff
@@ -78,7 +78,27 @@ public TimePicker() {
...
-        super(time, null, String.class, PARSER, FORMATTER);
+        this(time, false);
+    }
+
+    /**
+     * Convenience constructor to create a time picker with a pre-selected time.
+     * <p>
+     * If {@code isInitialValueOptional} is {@code true} then the initial value
+     * is used only if element has no {@code "value"} property value, otherwise
+     * element {@code "value"} property is ignored and the initial value is set
```
Comment (mshabarov) [inline vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/TimePicker.java]: Again, this paragraph repeats the that is said below, maybe better to make it shorter, like this: 'Allows to choose whether to always use the provided time initial value or not'.

File: vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java (hunk 2 above)
Comment (mshabarov) [reply vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java]: The rule here is to use `isInitialValueOptional=true` when constructor has no init value in arguments as in this particular case, right? `false` otherwise. Is so, just forget my comment.

File: vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java [hunk 4]
```diff
@@ -15,18 +15,39 @@
...
+import com.vaadin.flow.server.VaadinSession;
 
 public class TimePickerTest {
 
+    private static LocalTime TEST_VALUE = LocalTime.now();
+
+    private static class TestTimePicker
+            extends GeneratedVaadinTimePicker<TestTimePicker, LocalTime> {
+
+        TestTimePicker() {
```
Comment (mshabarov) [inline vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java:45]: Does it make sense to test the case with mandatory init value (`TimePicker(LocalTime time)`) ?

**Review by mshabarov — CHANGES_REQUESTED** [review]

File: vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java (hunk 1 above)
Comment (denis-anisimov) [reply vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java:845]: May be yes, may be not: people are reading only one part and don't read the parameters explanation if they read javadocs at all.
I don't know/care. Let's remove.

File: vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java (hunk 4 above)
Comment (denis-anisimov) [reply vaadin-time-picker-flow/src/test/java/com/vaadin/flow/component/timepicker/tests/TimePickerTest.java:45]: There is already such test `setInitialValue`

File: vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java (hunk 2 above)
Comment (denis-anisimov) [reply vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java]: That's a mistake.
Thanks.

Comment (denis-anisimov) [reply vaadin-time-picker-flow/src/main/java/com/vaadin/flow/component/timepicker/GeneratedVaadinTimePicker.java]: Although it doesn't matter which value is used here.
`null`  as initial value makes it extra.

**Review by mshabarov — APPROVED** [review]
